name: build-test-deploy
on:
    workflow_dispatch:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-test-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: checkout the repository
                uses: actions/checkout@v4

            -   name: Setup Java
                uses: ./.github/actions/setup-java

            -   name: Setup Maven
                uses: ./.github/actions/setup-maven

            -   name: Build and Test
                continue-on-error: true
                run: ./mvnw clean verify

            -   name: Publish to Github Packages
                run: ./mvnw deploy -Pdeployable-jar
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#               momentarily deactivate quality gate
#            -   name: Run Code Quality Check
#                uses: ./.github/actions/code-quality
